### ISSUE TITLE
Change lyrics provider please !!!

### ISSUE THREAD

**Issue by pafofi** [cbyrne/LyricifyBugTracker#30]
I bought this tweak a few weeks ago but it is properly unasable because 99,9% of time the lyrics are totally wrong and unrelevant. 
Please make it use another database because it make this beautiful made tweak just pointless...
FWIW I downloaded musilyrics from Julio Verne which works perfectly at every attempt. It is definitely not as beautiful but may you use the same lyric provider ?! Hope you’ll take care of my request and all the best.

**Comment by cbyrne** [comment]
Contact support@ksoft.si
